### PR TITLE
Namespace the "disabled" class name

### PR DESCRIPTION
**Pull request by romgain**
Hi @theanam ! Thanks a lot for this great library!

This PR prefixes the `disabled` classname with `lb-`.
`disabled` is a fairly common class name, and clashes with existing style definitions on a project that I'm working on. 
This change should be transparent for this library, but will reduce the likeliness of classname conflicts.

### CODE REVIEW

**Comment by theanam** [comment]
hello @romgain , the changes look good. could you change the version on package.json to `1.8.0` please. that way merge would automatically publish the changes to npm

**Comment by romgain** [comment]
Amazing, thanks @theanam !

Will do now.

Would you also be opened to relaxing the peer dependency requirements to include react 17?
If so, I'd be happy to do this, either as part of this PR, or a new one, whichever has your preference

**Comment by theanam** [comment]
Sure. I forgot to change it. you can add it as a part of the PR

**Comment by romgain** [comment]
Done. Thanks again :+1:

**Pull request merged**
